### ISSUE TITLE
Problem with the  bootsnap dependency

### ISSUE THREAD

**Issue by artero** [MarsBased/pathfinder-rails#90]
Problem when run the `rails new -m ...` command:

```
Traceback (most recent call last):
	15: from bin/rails:3:in `<main>'
	14: from bin/rails:3:in `load'
	13: from /Users/juan/projects/Zemobile/passport/bin/spring:15:in `<top (required)>'
	12: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	11: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	10: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	 9: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	 8: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	 7: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	 6: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	 5: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	 4: from /Users/juan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	 3: from /Users/juan/projects/Zemobile/passport/bin/rails:8:in `<top (required)>'
	 2: from /Users/juan/projects/Zemobile/passport/bin/rails:8:in `require_relative'
	 1: from /Users/juan/projects/Zemobile/passport/config/boot.rb:4:in `<top (required)>'
/Users/juan/projects/Zemobile/passport/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
```

**Comment by dvdgs88** [comment]
Already fixed on https://github.com/MarsBased/pathfinder-rails/commit/c57db4457cc0e171e4e5b56f2ecfd093ef619dd5
